sudo: required
services:
  - docker

before_install:
  - docker build -t geemike/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true geemike/react-test npm test  

after_success:
  - docker build -t geemike/multi-client ./client
  - docker build -t geemike/multi-nginx ./nginx
  - docker build -t geemike/multi-server ./server
  - docker build -t geemike/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push geemike/multi-client:$TRAVIS_BUILD_NUMBER 
  - docker push geemike/multi-nginx:$TRAVIS_BUILD_NUMBER 
  - docker push geemike/multi-server:$TRAVIS_BUILD_NUMBER  
  - docker push geemike/multi-worker:$TRAVIS_BUILD_NUMBER 

#deploy:
# provider: elasticbeanstalk
#  region: us-east-1
#  app: effective-chainsaw
#  env: EffectiveChainsaw-env
#  bucket_name: elasticbeanstalk-us-east-1-101544221200
#  bucket_path: docker-multi
#  on:
# branch: master
#  access_key_id: 
# secure: $AWS_ACCESS_KEY
#  secret_access_key:
# secure: $AWS_SECRET_KEY
  
    